In [4]:
import numpy as np
from scipy.spatial.transform import Rotation as R
from spatialmath import SE3
def pose_to_matrix(px, py, pz, qx, qy, qz, qw):
    T = np.eye(4)
    T[:3, :3] = R.from_quat([qx, qy, qz, qw]).as_matrix()
    T[:3, 3] = [px, py, pz]
    return T

In [5]:
tag_T_ee = SE3().Tz(0.06) @ SE3().Rz(90, unit='deg') @ SE3.Ry(-90, unit='deg')

NameError: name 'ee_T_base' is not defined

In [7]:
ee_T_base = pose_to_matrix(
    0.5984203219413757,
    0.3618444502353668,
    0.20653866231441498,
    -0.22004627779213634,
    0.6877651406407475,
    0.6383786905712042,
    0.2665171558715004,
)
tag_T_base = ee_T_base @ tag_T_ee.A
cam_T_base = np.array([
    [ 0.0241404614906644, -0.44315264823165645,  0.8961210679837226, -0.09965914957225427],
    [-0.9993724798166944, -0.03393909490325564,  0.010138265245033196, 0.47240773540515774],
    [ 0.02592073887929497,-0.8958034763286074,  -0.4436938664141459, 0.4392741508201531],
    [0,0,0,1]
])

tag_T_cam = np.linalg.inv(cam_T_base) @ tag_T_base

print(tag_T_cam)

[[-0.99382056  0.07273198  0.08384964  0.06168396]
 [-0.03332772 -0.91608176  0.39960414 -0.09911775]
 [ 0.10587713  0.39434029  0.91284488  0.73405874]
 [ 0.          0.          0.          1.        ]]


In [8]:
tag_T_base

array([[ 0.08565671,  0.76109648,  0.64295806,  0.60355972],
       [ 0.99540144, -0.03759743, -0.08810457,  0.42156854],
       [-0.04288251,  0.64754813, -0.760817  ,  0.20396571],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [34]:
ee_T_base

array([[-0.76109648, -0.64295806,  0.08565671,  0.59842032],
       [ 0.03759743,  0.08810457,  0.99540144,  0.36184445],
       [-0.64754813,  0.760817  , -0.04288251,  0.20653866],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

### base_T_tool

```text
[-0.7611  -0.6430   0.0857   0.5984]
[ 0.0376   0.0881   0.9954   0.3618]
[-0.6476   0.7608  -0.0429   0.2065]
[ 0.0000   0.0000   0.0000   1.0000]
```

### cam_T_tag

```text
[-0.9973   0.0312   0.0664   0.0373]
[-0.0035  -0.9242   0.3818  -0.1033]
[ 0.0733   0.3806   0.9218   0.7107]
[ 0.0000   0.0000   0.0000   1.0000]
```